/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_iscas_tcse_favtrigger_instrumenter_SysTime */

#ifndef _Included_edu_iscas_tcse_favtrigger_instrumenter_SysTime
#define _Included_edu_iscas_tcse_favtrigger_instrumenter_SysTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_iscas_tcse_favtrigger_instrumenter_SysTime
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_iscas_tcse_favtrigger_instrumenter_SysTime_rdtsc
  (JNIEnv *, jclass);

/*
 * Class:     edu_iscas_tcse_favtrigger_instrumenter_SysTime
 * Method:    rdtscp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_iscas_tcse_favtrigger_instrumenter_SysTime_rdtscp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
