docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"create 'test', 'cf'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"list 'test'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"put 'test', 'row1', 'cf:a', 'value1'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"put 'test', 'row2', 'cf:b', 'value2'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"put 'test', 'row3', 'cf:c', 'value3'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"put 'test', 'row4', 'cf:d', 'value4'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"scan 'test'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"get 'test', 'row1'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"disable 'test'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"get 'test', 'row2'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"enable 'test'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"get 'test', 'row3'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"disable 'test'\" | bin/hbase shell -n"
docker exec -t C1hb-cli /bin/bash -ic "cd /home/gaoyu/evaluation/hbase-2.4.8 && echo \"drop 'test'\" | bin/hbase shell -n"
